[workspace]
members = [
  "crates/hyperinfer-core",
  "crates/hyperinfer-client",
  "crates/hyperinfer-server",
  "crates/hyperinfer-python",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
